### ISSUE TITLE
Update csv saver to use prefix 'ddf--' instead of 'dd_'

### ISSUE THREAD

**Issue by olarosling** [open-numbers/py-scripts#1]
Instead of hunting down xlsx files with file name prefix "dd_" , it should look for "ddf--" and a sheet called output.
Try it by checing out this repo, run the script, and commit the repo with the new csv files.
https://github.com/open-numbers/ddf--gapminder--geo_countries_and_groups

**Comment by finarb** [comment]
This should not be an issue......same logic and same call...so now the call will be like

sudo python <script path and name> <parent directory> <dd> 

code is flexible to take anything as starting letter or letters...

**Comment by olarosling** [comment]
I redefined this issue, now that we have new prefix

**Comment by finarb** [comment]
Can this issue be closed? its working on the above mentioned folder

**Comment by olarosling** [comment]
Yes it works. Is there a test written that can be run to ensure it continues to work as we keep adding to the script? And descriptions of how to run the test?

**Comment by finarb** [comment]
Closing this now.....I will however update the description in a day or so
