### ISSUE TITLE
Save all as csv should accept files missing sheet "output" 

### ISSUE THREAD

**Issue by olarosling** [open-numbers/py-scripts#6]
https://github.com/open-numbers/py-scripts/blob/master/scripts/utils/save_all_as_csv.py

If xlsx has not output sheet 
A. if file has only onn wheet, 
then 
-  use that sheet 
-  and print this this in the CMD as a 
"WARNING : Couldn't find "output" sheet. Saved the only sheet in [FILENAME]

B. If the file has multiple sheet, and non of them are called "output"
-  if all other sheets are empty, follow procedure A
- else
 dont save any sheet 
 and print this this in the CMD as a:
"WARNING : Couldn't find "output" sheet. Didn't save: [FILENAME]

**Comment by finarb** [comment]
Do you want error in cmd or in a log file?

**Comment by olarosling** [comment]
cmd please

**Comment by finarb** [comment]
whatif the file has multiple sheets ....none named output,.....but two sheets have data? is this a possibility I should account for or this cannot happen?

-Regards,
Abhishek

**Comment by finarb** [comment]
Also I am determining if an excel sheet is empty by checking if there is any data in cell A1.
Is this condition ok or not. Please let me know.

Regards,
Abhishek
